### ISSUE TITLE
iOS App failing to subscribe

### ISSUE THREAD

**Issue by mickeymousse** [DigitaSecurity/DND-Issues#22]
Hi,

The subscription doesn"t work.
If I choose a month subscription, it display "Transaction failed".
If I want to restore a previous purchase, it display : "Oh No!... Unable to complete transation. Please try again".

After I've added my macbook as a paired device, it is disconnect every times, but the "Test Device Pairing" button is working.

I'm on a iphone 8+ with IOS 11.3.1 and my macbook is a MPB 15" 2016.

**Comment by josh-stein** [comment]
@mickeymousse 

Thank you for filing this issue. Here are a few notes that may explain the issue you are seeing:

* A valid registration/pairing is required for the subscription receipt to be successfully sync'd to our backend (i.e. the certs/keys synced from your macOS is what allows the iOS app to talk to our backend). We will enter a ticket to make this error more explicit.
* If you have already gone through the process of subscribing, once a valid pairing is made and Apple re-pushes us the receipt, we should acknowledge the subscription.

Here are steps to possibly address your subscription issue:
* Make sure you have a macOS device successfully paired 
* Close the iOS the app and reopen it. Open the subscription page and wait for it to update/load.
* If you have already completed the purchase you should not have to repurchase and/or restore.

As for the "Disconnect" please note:
* Your laptop is only connected for 5 minutes after each alert (lid open event). 
* When you trigger connection with a lid open event, does it still read "Disconnected"? 

If this does not work as expected. Please follow the steps here: https://digitasecurity.com/product/donotdisturb/#troubleshooting and send the requested details to dnd@digitasecurity.com so that we can open up a 1:1 support ticket.

**Comment by mickeymousse** [comment]
Thanks, everything works !
