### ISSUE TITLE
Mojave (Beta 7): Taking pictures with app fail with "Error Performing Action"

### ISSUE THREAD

**Issue by PokeCaptain** [DigitaSecurity/DND-Issues#29]
Pretty much the title. Going into the event logs shows a picture "Zero KB" and a status of "2". This may be due to a conflict with OverSight, but that program has given me no prompts that DND wants to use the camera.

**Comment by josh-stein** [comment]
According to @pwardle, Oversight should not block without prompting you -- so that is probably not the culprit. 

Can you please send the output from the log command found in our [troubleshooting guide](https://digitasecurity.com/donotdisturb/userguide/#troubleshooting) to dnd@digitasecurity.com.

Specifically, I've attached a screen capture of item 4 (note: the '$' should not be retyped. It is representative of the command prompt). 

<img width="1077" alt="screen shot 2018-08-14 at 9 39 04 pm" src="https://user-images.githubusercontent.com/11893877/44127325-d477a646-a00a-11e8-8a14-a2bb6246d74e.png">

Better yet, you may additionally want to use the start and end parameters to narrow down the log output (around the date/time you see the failure), like so: `log show --start 2018-08-11 --end 2018-08-12 | grep -i disturb`

**Comment by PokeCaptain** [comment]
Email Sent! Let me know if I can help further!

**Comment by josh-stein** [comment]
@PokeCaptain Thank you!
 
After reviewing the provided information, 99% sure this is an issue introduced in Mojave, with some additional protections Apple is rolling out for camera use by installed apps.
 
@pwardle  did a write up on this that includes an introduction to some of the protections in Mojave if interested in details (ignoring for now the 'breaking' part): https://objective-see.com/blog/blog_0x2F.html
 
Will dig further to see if there are ways to configure Mojave to allow our camera use. The lack of "Allow" prompt from the OS is suspect, and may indicate that we now need to issue the command from a user session, requiring a code change/refactor in our next release.

**Comment by uhlhosting** [comment]
Any news on this matter? i can confirm is not working on any version of mojave i had tested. Any eta for a release?

**Comment by josh-stein** [comment]
@uhlhosting Yes, its been confirmed that Mojave's new privacy features break our use of the camera. We can no longer issue the camera command from the background app and must first get user pre-authorization.

We are finishing up the development on these changes very soon. Barring any drastic last minute changes in the Mojave APIs, we should be in good shape to release a version with Mojave support shortly. We will know more upon Apple's next beta release, which we will aim to quickly follow with a (potentially beta) release of our own.

**Comment by josh-stein** [comment]
It should also be noted that having to issue the camera command from the user context (instead of the background daemon) does have the side affect of eliminating our ability to snap a photo if no user is logged in (i.e. you've logged off or shutdown rather than simply closed/locked).

**Comment by uhlhosting** [comment]
any plans to accept users in beta testing? I run all day long betas 🗡

**Comment by josh-stein** [comment]
Now available: https://digitasecurity.com/donotdisturb/versions/v1.3/
